CC		?= cc
GIT 		?= git
PKGCONF 	:= $(shell pkg-config --cflags xorg-server xproto)
XORGEXTDIR 	:= $(shell pkg-config --variable=moduledir xorg-server)/extensions

EXTRA_CFLAGS += $(PKGCONF)
EXTRA_CFLAGS += -fPIC -std=c99
EXTRA_CFLAGS += -Wall -Werror

SOURCES := rexsec.c Makefile README.rst ChangeLog.rst

all: rexsec.so

rexsec.so: rexsec.o
	$(CC) -o $@ -shared $(CFLAGS) $(EXTRA_CFLAGS) $<

rexsec.o: rexsec.c version.h
	$(CC) -c rexsec.c $(CFLAGS) $(EXTRA_CFLAGS)

VERSION: $(SOURCES)
	@if ! $(GIT) describe --tags > $@; then \
		rm $@; \
		false; \
	fi

version.h: VERSION
	@echo "/* DO NOT EDIT! This file is autogenerated by Makefile */" > $@
	@echo "#define VERSION \"$(shell cat VERSION)\"" >> $@
	@set -- $$(sed 's,\.,\n,g' VERSION |sed 's,[^[:digit:]].*$$,,') && \
		echo "#define MAJORV $$1" >> $@ && \
		echo "#define MINORV $$2" >> $@ && \
		echo "#define PATCHL $$3" >> $@

xext-rexsec-%.tar.gz: $(SOURCES) VERSION
	@test "$$(cat VERSION)" = "$*"
	tar -czf $@ $^

check-release-tags:
	@set -- $$($(GIT) tag --points-at HEAD); \
	if [ "$$#" -gt 1 ]; then \
		echo "Error: multiple tags point at HEAD:" >&2; \
		printf '  %s\n' "$$@" >&2; \
		exit 1; \
	fi

tarball: check-release-tags VERSION
	@$(MAKE) xext-rexsec-$$(cat VERSION).tar.gz

install: rexsec.so
	install -m644 -pD rexsec.so $(DESTDIR)$(XORGEXTDIR)/rexsec.so

clean:
	-rm -f rexsec.o VERSION version.h

distclean: clean
	-rm rexsec.so

.PHONY: all check-release-tags clean distclean install tarball
