GIT 		?= git
PKGCONF 	:= $(shell pkg-config --cflags xorg-server xproto)
XORGEXTDIR 	:= $(shell pkg-config --variable=moduledir xorg-server)/extensions
TYPOEXTDIR 	:= $(shell pkg-config --variable=moduledir xorg-server)/extenstions

EXTRA_CFLAGS += $(PKGCONF)
EXTRA_CFLAGS += -fPIC -std=c99
EXTRA_CFLAGS += -Wall -Werror

SOURCES := altsec.c Makefile README.rst

all: altsec.so

altsec.so: altsec.o
	cc -o altsec.so -shared $(CFLAGS) $(EXTRA_CFLAGS) altsec.o

altsec.o: altsec.c version.h
	cc -c altsec.c $(CFLAGS) $(EXTRA_CFLAGS)

VERSION: $(SOURCES)
	@if ! $(GIT) describe --tags > $@; then \
		rm $@; \
		false; \
	fi

version.h: VERSION
	@echo "/* DO NOT EDIT! This file is autogenerated by Makefile */" > $@
	@echo "#define VERSION \"$(shell cat VERSION)\"" >> $@
	@set -- $$(sed 's,\.,\n,g' VERSION |sed 's,[^[:digit:]].*$$,,') && \
		echo "#define MAJORV $$1" >> $@ && \
		echo "#define MINORV $$2" >> $@ && \
		echo "#define PATCHL $$3" >> $@

xext-altsec-%.tar.gz: $(SOURCES) VERSION
	@test "$$(cat VERSION)" = "$*"
	tar -czf $@ $^

tarball: VERSION
	@$(MAKE) xext-altsec-$(shell cat VERSION).tar.gz

fix-path:
	@test -d $(DESTDIR)$(TYPOEXTDIR) && \
		mkdir -p $(DESTDIR)$(XORGEXTDIR) && \
		rm -f $(DESTDIR)$(TYPOEXTDIR)/altsec.so && \
		rmdir $(DESTDIR)$(TYPOEXTDIR) && \
		ln -rs $(DESTDIR)$(XORGEXTDIR) $(DESTDIR)$(TYPOEXTDIR) ||:

install: fix-path altsec.so
	install -pD altsec.so $(DESTDIR)$(XORGEXTDIR)/altsec.so

clean:
	-rm -f altsec.o VERSION version.h

distclean: clean
	-rm altsec.so

.PHONY: all clean distclean fix-path install tarball
