name: Release Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm

    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get -y upgrade
          apt-get install -y gcc git make pkg-config libxext-dev xserver-xorg-dev

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git safe directory
        run: git config --global --add safe.directory $(pwd)

      - name: Build tarball
        run: make tarball

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: xext-rexsec-*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
