name: Release Build

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get -y upgrade
          apt-get install -y gcc git make pkg-config libxext-dev xserver-xorg-dev

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git safe directory
        run: git config --global --add safe.directory $(pwd)

      - name: Build tarball
        run: make tarball

      - name: Upload Tarball as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-tarball
          path: ./xext-rexsec-${{ github.ref_name }}.tar.gz
          retention-days: 1

  release:
    runs-on: ubuntu-latest
     needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Tarball
        uses: actions/download-artifact@v4
        with:
          name: release-tarball

      - name: Import Public Key
        run: |
          echo "${{ secrets.GPG_PUBLIC_KEY }}" | gpg --import

      - name: Verify Signature
        run: |
          if ! git verify-tag ${{ github.ref_name }}; then
            echo "Error: Tag is not signed or signature is invalid."
            exit 1
          fi

      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} ./xext-rexsec-${{ github.ref_name }}.tar.gz \
            --title "Release ${{ github.ref_name }}" \
            --generate-notes
